SELECT*FROM Electricity_connection_type ORDER BY connection_name ASC;
SELECT*FROM building_type ORDER BY name ASC;
CREATE TABLE building(id int(11) primary key,owner_name varchar(100) not null, address varchar(100) not null,building_type_id int(11) not null,email_address varchar(100),foreign key(building_type_id) references building_type(id));
INSERT INTO building(id,owner_name,address,building_type_id,email_address)VALUES(123,'tamannah','pune',10,'tam@gmail.com');
INSERT INTO building(id,owner_name,address,building_type_id,email_address)VALUES(456,'ram','mumbai',7,'ram@gmail.com');
INSERT INTO building(id,owner_name,address,building_type_id,email_address)VALUES(452,'chai','kolkata',8,'chai@gmail.com');
INSERT INTO building(id,owner_name,address,building_type_id,email_address)VALUES(254,'prabha','hyderabad',9,'praba@gmail.com');
SELECT*FROM building ORDER BY owner_name ASC;
SELECT*FROM electricity_reading ORDER BY total_units DESC;
SELECT meter_number FROM meter;
SELECT owner_name,contact_number FROM building ORDER BY owner_name ASC;
SELECT total_units,payable_amount,fine_amount FROM bill ORDER BY total_units DESC;
SELECT*FROM slab ORDER BY from_unit ASC;
SELECT owner_name FROM building WHERE owner_name LIKE 'Nicholas';
SELECT*FROM bill WHERE total_units>10000 ORDER BY total_units DESC;
SELECT * FROM bill WHERE due_date = ‘01/10/2017’ ORDER BY payable_amount DESC;
SELECT owner_name, address , contact_number FROM building WHERE email_address = null ORDER BY owner_name ASC;
SELECT * FROM building WHERE owner_name LIKE 'M%' ORDER BY owner_name ASC;
SELECT * FROM building WHERE building_type_id =2 ORDER BY owner_name ASC;
SELECT * FROM electricity_reading WHERE total_units BETWEEN 500 AND 1000 ORDER BY total_units ASC;
SELECT meter_id, total_units FROM electricity_reading WHERE h13<h14 ORDER BY total_units DESC;